function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()

	--rmodmi8lb
	-- AddTextEntry('0x05577318', 'Tuning 1')
	-- AddTextEntry('0x0770291C', 'Tuning 2')
	-- AddTextEntry('0x0BAE23B0', 'Tuning 3')
	-- AddTextEntry('0x5C1DF02F', 'Tuning 4')

	--mxpan_roof
	AddTextEntryByHash(GetHashKey("mxpan_roof"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mxpan_wing1"),"Tuning 02")
	--xkr
	AddTextEntryByHash(GetHashKey("xkgt_bonnet"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("xkgt_boot"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("xkgt_bumper_f"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("xkgt_bumper_f_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("xkgt_bumper_r"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("xkgt_skirt"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("xkgt_wing"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("xkgt_wing_2"),"Tuning 08")

	--wildtrak
	AddTextEntryByHash(GetHashKey("bronco_backwheel"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bronco_bumppainted"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("bronco_textpainted"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("softtop_bronco"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("softtop_bronco_primary"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("softtop_bronco_secondary"),"Tuning 06")

	--trx
	AddTextEntryByHash(GetHashKey("trx_bed_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("trx_bed_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("trx_cage_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("trx_split_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("trx_wing_1"),"Tuning 05")
		
	--nissantitan17
	AddTextEntryByHash(GetHashKey("nissantitan17_cage1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissantitan17_cage2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissantitan17_exh1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissantitan17_grill_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissantitan17_roof"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissantitan17_skirt1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissantitan17_wing_1"),"Tuning 07")

	--skr
	AddTextEntryByHash(GetHashKey("white"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("white2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("removeplatesupport"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("removemr"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("removeb"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("red"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("protector1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("protector2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("protector3"),"Tuning 09")

	--
	AddTextEntryByHash(GetHashKey("ack_grill_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ack_grill_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ack_grill_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ack_grill_4"),"Tuning 04")

	--cb500f
	AddTextEntryByHash(GetHashKey("bodyshell_2"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("bodyshell_3"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("fender_f"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("heads_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("proliner_exh"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("proliner_exh_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("proliner_long_exh"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("proliner_long_exh_2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("scorpion_exh"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("single_seat"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("single_seat_2"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("single_seat_3"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("single_seat_4"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("tail"),"Tuning 14")

	--z1000
	AddTextEntryByHash(GetHashKey("z1000_chain"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("z1000_exh_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("z1000_exh_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("z1000_exh_3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("z1000_light1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("z1000_light2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("z1000_light3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("z1000_light4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("z1000_light5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("z1000_light6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("z1000_light7"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("z1000_light8"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("z1000_null"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("z1000_null2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("z1000_null3"),"Tuning 15")

	--ttrs
	AddTextEntryByHash(GetHashKey("ttrs_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ttrs_bumf_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ttrs_bumf_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ttrs_bumf_4"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("ttrs_bumr_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("ttrs_bumr_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("ttrs_mir_l"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("ttrs_mir_l2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("ttrs_mir_r"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("ttrs_mir_r2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("ttrs_skirt_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("ttrs_skirt_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("ttrs_spoil_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("ttrs_spoil_2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("ttrs_spoil_3"),"Tuning 15")
	--kiagt
	AddTextEntryByHash(GetHashKey("kiagt_bumper_f_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("kiagt_bumper_f_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("kiagt_bumper_r_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("kiagt_door_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("kiagt_door_2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("kiagt_skirt_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("kiagt_spoiler_1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("kiagt_spoiler_2"),"Tuning 08")
	--cl65
	AddTextEntryByHash(GetHashKey("cl65_bonnet_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("cl65_bumf_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("cl65_exh_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("cl65_exh_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("cl65_exh_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("cl65_exh_4"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("cl65_intercooler"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("cl65_intercooler2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("cl65_race_int"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("cl65_roof"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("cl65_side_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("cl65_side_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("cl65_splitter_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("cl65_wing_2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("cl65_wing_4"),"Tuning 15")
	--aaq4
	AddTextEntryByHash(GetHashKey("aaq4_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("aaq4_bumr_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("aaq4_chassis_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("aaq4_ext"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("aaq4_spoiler_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("aaq4_wingl_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("aaq4_wingr_1"),"Tuning 07")
	--fk2
	AddTextEntryByHash(GetHashKey("fk2_wfp_2"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("fk2_wfp_3"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("fk2_wfp_4"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("fk2_wlfp_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("fk2_wlfp_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("fk2_wlfp_4"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("fk2_wlmp_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("fk2_wlmp_3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("fk2_wlmp_4"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("fk2_wrfp_2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("fk2_wrfp_3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("fk2_wrfp_4"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("fk2_wrmp_2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("fk2_wrmp_3"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("fk2_wrmp_4"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("fk2_wrp_2"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("fk2_wrp_3"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("fk2_wrp_4"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("modulo_fk2_1"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("modulo_fk2_2"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("modulo_fk2_3"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("modulo_fk2_4"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("modulo_fk2_5"),"Tuning 23")
	--h2carb
	AddTextEntryByHash(GetHashKey("h2r_charger"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("h2r_duct"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("h2r_exhaust"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("h2r_panel"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("h2r_wing_l"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("h2r_wing_u"),"Tuning 06")
	--veln
	AddTextEntryByHash(GetHashKey("veln_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("veln_bumr_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("veln_exh_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("veln_skirt_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("veln_spoiler_1"),"Tuning 05")
	--monza
	AddTextEntryByHash(GetHashKey("aero_super"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("aeroef"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("backlip"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("bigga_ex"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("bosozoku"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("capa_d"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("capa_e"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("cibie"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("cibie_2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("coluna_b"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("double_ex"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("ducktail1"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("ducktail2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("e_preto"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("fog_capa"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("fog_ok"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("front_lip"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("recaro"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("sem_e"),"Tuning 19")
	AddTextEntryByHash(GetHashKey("sport_spoiler"),"Tuning 20")
	--cb650r
	AddTextEntryByHash(GetHashKey("cb650r_mods_exh"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("cb650r_mods_exh2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("cb650r_mods_seat1"),"Tuning 03")
	--xt660
	AddTextEntryByHash(GetHashKey("xt660_cano_a"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("xt660_churra_a"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("xt660_escape_b"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("xt660_ferros_a"),"Tuning 04")
	--xj6
	AddTextEntryByHash(GetHashKey("xj6_cano_a"),"Tuning 01")
	--hornet
	AddTextEntryByHash(GetHashKey("hornet_cano_a"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("hornet_escape_a"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("hornet_suporte_a"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("hornet_suporte2_a"),"Tuning 04")
	--toyotasupra
	AddTextEntryByHash(GetHashKey("toyotasupra_bumprr"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("toyotasupra_cage"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("toyotasupra_cage_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("toyotasupra_roof"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_4"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_5"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_6"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_7"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_8"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_9"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("toyotasupra_wing_10"),"Tuning 13")
	--tiger
	AddTextEntryByHash(GetHashKey("tiger_bau_a"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("tiger_cano_a"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("tiger_ferros_a"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("tiger_suporte_a"),"Tuning 04")
	--titan160
	AddTextEntryByHash(GetHashKey("titan160_cap_a"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("titan160_delata_a"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("titan160_matacachorro_a"),"Tuning 03")
	--r8c20
	AddTextEntryByHash(GetHashKey("r8c20_roof_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("r8c20_roof_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("r8c20_roof_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("r8c20_wing_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("r8c20_wing_2"),"Tuning 05")
	--r125
	AddTextEntryByHash(GetHashKey("r125_d_bubble"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("r125_exh_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("r125_exh_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("r125_exh_3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("r125_h_guard"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("r125_pegs_r"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("r125_slider"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("r125_t_bag"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("r125_t_pad"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("r125_ttidy"),"Tuning 10")
	--nissanskyliner34
	AddTextEntryByHash(GetHashKey("nissanskyliner34_bnt_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_bumr_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_bumr_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_exh_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_skirt_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_skirt_2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_split_1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_split_2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("nissanskyliner34_spoil_1"),"Tuning 09")	
	--gtr
	AddTextEntryByHash(GetHashKey("gtr_arch_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("gtr_arch_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("gtr_bumf_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("gtr_bumf_2"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("gtr_bumf_3"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("gtr_bumr_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("gtr_bumr_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("gtr_bumr_3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("gtr_hood_1"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("gtr_skirt_1"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("gtr_skirt_2"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("gtr_skirt_3"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("gtr_wing_1"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("gtr_wing_2"),"Tuning 14")	
	AddTextEntryByHash(GetHashKey("gtr_wing_3"),"Tuning 15")
	--gtr
	AddTextEntryByHash(GetHashKey("mazdarx7_bodyshell_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_4"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_5"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_6"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_7"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_8"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("mazdarx7_bumf_9"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_2"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_3"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_4"),"Tuning 14")	
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_5"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_6"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_7"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_8"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("mazdarx7_bumr_9"),"Tuning 19")	
	AddTextEntryByHash(GetHashKey("mazdarx7_door_mirror_l"),"Tuning 20")
	AddTextEntryByHash(GetHashKey("mazdarx7_door_mirror_r"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_1"),"Tuning 21")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_2"),"Tuning 22")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_3"),"Tuning 23")	
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_4"),"Tuning 24")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_5"),"Tuning 25")
	AddTextEntryByHash(GetHashKey("mazdarx7_exh_6"),"Tuning 26")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_1"),"Tuning 27")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_2"),"Tuning 28")
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_3"),"Tuning 29")	
	AddTextEntryByHash(GetHashKey("mazdarx7_hood_4"),"Tuning 30")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_1"),"Tuning 31")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_2"),"Tuning 32")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_3"),"Tuning 33")	
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_4"),"Tuning 34")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_5"),"Tuning 35")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_6"),"Tuning 36")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_7"),"Tuning 37")	
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_8"),"Tuning 38")
	AddTextEntryByHash(GetHashKey("mazdarx7_skirts_9"),"Tuning 39")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_1"),"Tuning 40")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_2"),"Tuning 41")	
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_3"),"Tuning 42")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_4"),"Tuning 43")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_5"),"Tuning 44")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_6"),"Tuning 45")
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_7"),"Tuning 46")	
	AddTextEntryByHash(GetHashKey("mazdarx7_spoiler_8"),"Tuning 47")
	--lancerevolutionx
	AddTextEntryByHash(GetHashKey("lancerevolutionx_cage"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh2"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_exh3"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt1b"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt3"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt3b"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("lancerevolutionx_skirt4"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_1"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_1b"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_split_2"),"Tuning 13")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing0"),"Tuning 14")	
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing1"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing2"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing3"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("lancerevolutionx_wing4"),"Tuning 18")
	--lancerevolution9
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumf_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("lancerevolution9_bumr_3"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("lancerevolution9_exh_1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("lancerevolution9_hood_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_1"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("lancerevolution9_skirt_3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("lancerevolution9_wing_1"),"Tuning 12")
	--ferrariitalia
	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bnt3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bumr1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("ferrariitalia_bumr2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("ferrariitalia_ext1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("ferrariitalia_int_roll1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("ferrariitalia_int_roll2"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt1"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt2"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt3"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("ferrariitalia_skirt4"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("ferrariitalia_split1"),"Tuning 13")	
	AddTextEntryByHash(GetHashKey("ferrariitalia_split2"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("ferrariitalia_split3"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_1"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_2"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_3"),"Tuning 18")
	AddTextEntryByHash(GetHashKey("ferrariitalia_spoil_4"),"Tuning 19")
	--audirs7
	AddTextEntryByHash(GetHashKey("audirs7_blackchrome_rear"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("audirs7_bumper_f_1"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("audirs7_bumperr_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("audirs7_chrome_ch_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("audirs7_chrome_lf_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("audirs7_chrome_lr_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("audirs7_chrome_rf_1"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("audirs7_chrome_rr_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("audirs7_exhaust_1"),"Tuning 09")	
	AddTextEntryByHash(GetHashKey("audirs7_mirror_l_1"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("audirs7_mirror_l_2"),"Tuning 11")
	AddTextEntryByHash(GetHashKey("audirs7_mirror_r_1"),"Tuning 12")
	AddTextEntryByHash(GetHashKey("audirs7_mirror_r_2"),"Tuning 13")	
	AddTextEntryByHash(GetHashKey("audirs7_spoiler_1"),"Tuning 14")
	AddTextEntryByHash(GetHashKey("audirs7_spoiler_2"),"Tuning 15")
	AddTextEntryByHash(GetHashKey("audirs7_x_uk_1"),"Tuning 16")
	AddTextEntryByHash(GetHashKey("audirs7_x_uk_1l"),"Tuning 17")
	AddTextEntryByHash(GetHashKey("audirs7_x_uk_1r"),"Tuning 18")
	--audirs7
	AddTextEntryByHash(GetHashKey("a6_livery_1"),"Tuning 01")
	--audirs7
	AddTextEntryByHash(GetHashKey("675_bump_f"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("675_bump_r"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("675_chas_1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("675_door_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("675_door_2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("675_roof_1"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("675_roof_2"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("675_roof_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("675_spoiler_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("675_wing_1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("675_wing_2"),"Tuning 06")
end)